name: Destroy Infrastructure

on:
  workflow_dispatch:  # ⚠️ Esto lo vuelve manual

jobs:
  destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: envs/dev  # Ajusta si estás en otra carpeta

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
